### ISSUE TITLE
Update Bot Airtable to include missing fields

### ISSUE THREAD

**Issue by amsos** [Govrn-HQ/Movement-Proposals#17]
**Describe the change request**
There are missing members and tasks on the bot airtable form

**Future State**
Explain how the desired future state of the change.

Add the following fields:
     **Missing members:**
          Mika Reyes, Katya Ternopolska, Corina, Nettra Pan
     **Missing tasks:**
          Vote on a Proposal
          Sponsor a Proposal
          Process a Proposal
          Governance - Enter Movement Model Data
          :straight_ruler: Created a Poll
          :telephone_receiver: Attended Dao-wide Call
          Grants - promote & update grants criteria, outreach
          Grants - review applications (as part of a team)
          Grants - administration - followup, refinement, onboarding
          Grants - accounting and payments
          Treasury reports to the DAO (monthly or quarterly) - assets held, money in, money out in the period
          Fundraising - close a grant (upon receipt)
          Fundraising - create and deliver a marketing/outreach campaign
          Task that's included in the airtable bot form but not in the PRs:
          Donated on gitcoin grants

**Comment by christinevandev** [comment]
@hollygrimm @amsos It's not a problem for the algorithm, so no need to resubmit. If MGD decides to track it in the future, we can start adding it in and/or retroactively back update.

**Comment by amsos** [comment]
Awesome, going to close this comment.
